[build]
  base = "frontend"          # your frontend source folder (where package.json is)
  publish = "frontend/dist"     # folder containing the built static files
  command = "npm run build"     # build command for Netlify

# SPA routing: send all unmatched routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
